using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;

//è¿™æ˜¯è„‘ç¥ç»çš„ä»£ç 
public class Brain : MonoBehaviour
{
    public float disappearDalay = 1f;//æ¶ˆå¤±å»¶è¿Ÿæ—¶é—´å­—æ®µ
    public float reappearDalay = 2f;//å‡ºç°å»¶è¿Ÿæ—¶é—´å­—æ®µ
    //Rendererå’ŒColliderçš„ç»„ä»¶çš„è·å–
    public SpriteRenderer new_renderer;
    public BoxCollider2D new_collider;

    private void Start()
    {
        new_renderer = GetComponent<SpriteRenderer>();
        new_collider = GetComponent<BoxCollider2D>();
    }
    private void OnCollisionEnter2D(Collision2D collision)
    {
        //å¦‚æœå’Œç©å®¶ç¢°æ’
        if (collision.gameObject.tag.Equals("Player"))
        {
            //è°ƒç”¨äº’åŠ¨é€»è¾‘çš„å‡½æ•°
            StartCoroutine(StartDisappearing());
        }
    }
    private void OnCollisionExit2D(Collision2D collision)
    {
        
        StopCoroutine(StartDisappearing());
    }

    //è„‘ç¥ç»äº’åŠ¨é€»è¾‘çš„å‡½æ•°ğŸ‘‡

    IEnumerator StartDisappearing()
    {
        //å»¶è¿Ÿ1sæ‰§è¡Œåé¢ä»£ç 
       yield return new WaitForSeconds(disappearDalay);
        
        //ç¦ç”¨æ¸²æŸ“å’Œç¢°æ’ï¼Œä¹Ÿå°±æ˜¯è§†è§‰ä¸Šçš„æ¶ˆå¤±
        new_renderer.enabled = false;
        new_collider.enabled = false;
        
        //ç©å®¶æ­¤æ—¶æ‰è½ï¼Œå»¶è¿Ÿ2s
        yield return new WaitForSeconds(reappearDalay);
        
        //å¯ç”¨æ¸²æŸ“å’Œç¢°æ’ï¼Œä¹Ÿå°±æ˜¯è§†è§‰ä¸Šçš„å‡ºç°
        new_renderer.enabled = true;
        new_collider.enabled = true;
    }

}
