using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class MedullaManager : MonoBehaviour
{
    //å…³å¡ä¸­çš„â€œé«“è´¨â€è¿™ä¸ªç‰©å“çš„åˆ—è¡¨ï¼ˆä¸€å…³ä¸­æœ‰è‹¥å¹²ä¸ªé«“è´¨ï¼Œè¿™é‡Œé¢è®°å½•è¯¥å…³å¡æ‰€æœ‰é«“è´¨ï¼‰
    public List<Medulla> medullas;

    //ç”¨æ¥è®°å½•å·²ç»æ¿€æ´»çš„é«“è´¨ä¸ªæ•°ğŸ‘‡
    private int activeMedulla = 0;

    private void OnEnable()
    {
        throw new NotImplementedException();
        //ä»Medullaé‡Œçš„å‚æ•°
        Medulla.OnMedulla += OnMedulla;
    }

    private void OnDisable()
    {
        Medulla.OnMedulla -= OnMedulla;
    }

    private void Start()
    {
        //å¦‚æœæ²¡æœ‰é«“è´¨ï¼Œå°±ç›´æ¥è·å¾—é€šè¿‡æ¡ä»¶ï¼Œä¹Ÿå°±æ˜¯ä¸ä¼šè¢«é™åˆ¶æ´»åŠ¨
        if(medullas == null||medullas.Count==0)
        {
            Debug.Log("è¿™æ˜¯ä¸€ä¸ªæ²¡æœ‰é«“è´¨çš„å…³å¡");
            //è¿™æ˜¯ä¸€ä¸ªå¤„ç†é«“è´¨å…¨éƒ¨è¢«ç‚¹äº®çš„åé€»è¾‘çš„å‡½æ•°ğŸ‘‡ï¼Œåœ¨æœ«å°¾å¯ä»¥çœ‹åˆ°ä»£ç å†…å®¹ç‰©
            ProceedToNextScene();
        }
    }

    private void OnMedulla(Medulla medulla)
    {
        if (medullas.Contains(medulla))
        {
            //æ¿€æ´»é«“è´¨ä¸ªæ•°åŠ ä¸€
            activeMedulla++;
            Debug.Log($"é«“è´¨è¢«ç‚¹äº®! {activeMedulla}/{medullas.Count}");
            //å½“å…¨éƒ¨æ¿€æ´»çš„æ—¶å€™
            if (activeMedulla == medullas.Count)
            {
                Debug.Log("æ‰€æœ‰çš„é«“è´¨éƒ½è¢«ç‚¹äº®äº†");
                //é‚£å°±æ²¡æœ‰é™åˆ¶äº†ï¼Œå¯ä»¥å»å¾€å¯¹åº”çš„å…³å¡
                ProceedToNextScene();
            }
        }
        
    }

    private void ProceedToNextScene()
    {
        //è¿™é‡Œæ˜¯åˆ‡æ¢åˆ°ä¸‹ä¸€ä¸ªåœºæ™¯çš„é€»è¾‘ğŸ‘‡
        UnityEngine.SceneManagement.SceneManager.LoadScene("æœªçŸ¥åœºæ™¯å");
        //ä¸è¿‡è¿™ä¹ˆå†™çš„è¯å°±åªèƒ½åˆ‡æ¢åˆ°ç‰¹å®šçš„åœºæ™¯äº†ï¼Œæ„Ÿè§‰è¿™ä¸ªéœ€è¦ä¿®æ”¹ä¿®æ”¹ğŸ’¡ğŸ’¡ğŸ’¡
    }

}
